site_name: My Docs
nav:
  - Home: index.md
  - Nouvelle Page:
    - Fichier 1: fichier1.md
    - Nouveau Fichier: fichier2.md 
    - Autre: testfichier.md
extra_css:
  - PBstylesheets/PBextra.css

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
theme:
  name: mkdocs


